spring:
    application: 
        name: academic_service
    datasource:
        url: jdbc:mysql://localhost:3306/Academic_Service
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            minimum-idle: 5
            maximum-pool-size: 10
            idle-timeout: 600000
    jpa:
        hibernate:
            ddl-auto:  update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    profiles:
        active: dev
server:
  port: 8084
