spring:
    application: 
        name: ACADEMIC_SERVICE
    datasource:
        url: jdbc:mysql://localhost:3306/Academic_Service?createDatabaseIfNotExist=true
        username: root  
        password: password 
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            minimum-idle: 5
            maximum-pool-size: 10
            idle-timeout: 600000
    jpa:
        hibernate:
            ddl-auto:  update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    profiles:
        active: dev
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8086

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://eureka-server:8761/eureka/ # URL of the Eureka Server
#     registerWithEureka: true  # Register this client with Eureka
#     fetchRegistry: true  # Fetch the registry to discover other services
 
