spring:
  application:
    name: finance_service
    # file:
    #   uploads:
    #     photos-output-path: ./uploads
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/finance_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000 # 10 minutes
      pool-name: HikariCP # Optional for clarity in logs
  jpa:
    hibernate:
      ddl-auto: update
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

# Chapa Payment Gateway Configuration
chapa:
  api:
    url: https://api.chapa.co/v1
  secret:
    key: CHASECK_TEST-e9Fx9PFOSErlyR9uTaJx7sEgtxeWlSji
  callback:
    url: http://localhost:8087/api/finance/payments/process

server:
  port: 8087

PublicKey: CHAPUBK_TEST-2hYHCrRRvI95dm0C7D94xybSsK59AvOH
SecretKey: CHASECK_TEST-e9Fx9PFOSErlyR9uTaJx7sEgtxeWlSji
EncryptionKey: CG7RxF1PANgPnwUrNTh2UTju