server:
  port: 8761
management:
  endpoints:
    web:
      exposure:
        include: health
eureka:
  client:
    register-with-eureka: false  # Eureka Server doesn’t register itself
    fetch-registry: false       # Eureka Server doesn’t fetch registry
  server:
    enable-self-preservation: false  # Optional: for development