services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-next-app:latest
    container_name: next-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped