services:
  mysql-db:
    image: mysql:8.0
    ports:
      - "0.0.0.0:3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: toor
      MYSQL_PASSWORD: toor
      MYSQL_DATABASE: User_Service
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-proot_password",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.1.98:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    env_file:
      - ./backend/api-gateway/.env
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    environment:
      - HOST_IP=192.168.1.98
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  user-management:
    build:
      context: ./backend/User_Service
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8082:8082"
    depends_on:
      mysql-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.1.98:8082/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 4
    env_file:
      - ./backend/User_Service/.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.1.98:3306/User_Service?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=toor
      - SPRING_DATASOURCE_PASSWORD=toor
      - EUREKA_INSTANCE_HOSTNAME=10.194.53.26
      - HOST_IP=192.168.1.98
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build: ./frontend
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - api-gateway
    environment:
      - HOST=0.0.0.0
    env_file:
      - ./frontend/.env
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mysql-data:
  service-registry-data:

networks:
  app-network:
    driver: bridge
