import {
  FiGrid,
  FiDollarSign,
  FiClock,
  FiPackage,
  FiSettings,
  FiList,
  FiUserPlus,
  FiCamera,
  FiEye,
  FiClipboard,
  FiBarChart,
  FiActivity,
  FiTrendingUp,
  FiUsers,
  FiFileText,
} from "react-icons/fi";
import {
  FaSchool,
  FaRegPlusSquare,
  FaUsers,
  FaCalendarCheck,
  FaQrcode,
  FaGraduationCap,
  FaPlusCircle,
  FaFileImport,
  FaList,
} from "react-icons/fa";
import { FiClock, FiDollarSign, FiEye, FiGrid, FiList, FiPackage, FiSettings, FiUserPlus, FiCamera } from "react-icons/fi";

export const MENU_ITEMS = [
  {
    id: "dashboard",
    icon: FiGrid,
    label: "Dashboard",
    href: "/dashboard",
    roles: "",
  },
  {
    id: "school",
    icon: FaSchool,
    label: "School",
    href: "/school",
    roles: "",
  },
  {
    id: "createschool",
    icon: FaRegPlusSquare,
    label: "Create School",
    href: "/school/createschool",
    roles: "",
  },
  {
    id: "subscription",
    icon: FiDollarSign,
    label: "Subscription",
    href: "/subscription",
    roles: "",
  },
  {
    id: "pendingrequest",
    icon: FiClock,
    label: "Pending Request",
    href: "/pendingrequest",
    roles: "",
  },
  {
    id: "package",
    icon: FiPackage,
    label: "Package",
    href: "/package",
    roles: "",
  },
  {
    id: "academic",
    icon: FiSettings,
    label: "Academic",
    href: "/academic",
    roles: "",
    subItems: [
      {
        id: "subject",
        label: "Subject",
        href: "/academic/subject",
        roles: "",
      },
      {
        id: "subject-class",
        label: "Subject Class",
        href: "/academic/subject/class",
        roles: "",
      },
      {
        id: "class",
        label: "Class",
        href: "/academic/class",
        roles: "",
      },
      {
        id: "stream",
        label: "Stream",
        href: "/academic/stream",
        roles: "",
      },
      {
        id: "timetable",
        label: "Time Table",
        href: "/academic/timetable",
        roles: "",
      },
    ],
  },
  {
    id: "employee",
    icon: FaUsers,
    label: "Employees",
    href: "/employee",
    roles: "",
    subItems: [
      {
        id: "employee_list",
        icon: FiList,
        label: "Employee List",
        href: "/employee",
        roles: "",
      },
      {
        id: "add_employee",
        icon: FiUserPlus,
        label: "Add Employee",
        href: "/employee/addemployee",
        roles: "",
      },
    ],
  },
  {
    id: "attendance",
    icon: FaCalendarCheck,
    label: "Attendance",
    href: "/attendance",
    roles: "",
    subItems: [
      {
        id: "generate",
        icon: FaQrcode,
        label: "Generate QR Code",
        href: "/attendance/generate",
        roles: "",
      },
      {
        id: "scan",
        icon: FiCamera,
        label: "Scan QR Code",
        href: "/attendance/scan",
        roles: "",
      },
      {
        id: "list",
        icon: FiList,
        label: "Attendance List",
        href: "/attendance/list",
        roles: "",
      },
      {
        id: "view",
        icon: FiEye,
        label: "View Attendance",
        href: "/attendance/view",
        roles: "",
      },
    ],
  },
  {
    id: "assesment",
    icon: FiClipboard,
    label: "Assessment",
    href: "/assesment",
    roles: "",
    subItems: [
      {
        id: "assessment_list",
        icon: FiBarChart,
        label: "Assessment Entries",
        href: "/assesment",
        roles: "",
      },
      {
        id: "createanalytics",
        icon: FiActivity,
        label: "Assessment Analytics",
        href: "/assesment/analytics",
        roles: "",
      },
      {
        id: "progreess-trackers",
        icon: FiTrendingUp,
        label: "Progress Track",
        href: "/assesment/progress-tracker",
        roles: "",
      },
      {
        id: "roster",
        icon: FiUsers,
        label: "Roster",
        href: "/assesment/roster",
        roles: "",
      },
      {
        id: "report-card",
        icon: FiFileText,
        label: "Report Card",
        href: "/assesment/reportcard",
        roles: "",
      },
       
    ],
  },
  {
    id: "announcementandevent",
    icon: FiSettings,
    label: "Announcements",
    href: "/communication/event",
    roles: "", // Roles can be updated later for access control (e.g., "admin,teacher")
    subItems: [
      {
        id: "event",
        label: "Events",
        href: "/communication/event",
        roles: "",
      },
      {
        id: "allEvents",
        label: "All Events",
        href: "/communication/event",
        roles: "",
      },
      {
        id: "createEvent",
        label: "Create Event",
        href: "/communication/event/create",
        roles: "",
      },
      {
        id: "pendingApprovals",
        label: "Pending Approvals",
        href: "/communication/event/pending-approval",
        roles: "", // Restrict to admins; adjust based on your role system
      },
      {
        id: "myAnnouncement",
        label: "My Announcement",
        href: "/communication/event/my-pending",
        roles: "", // Available to all creators
      },
      {
        id: "draft",
        label: "My Draft",
        href: "/communication/event/draft",
        roles: "", // Available to all creators
      },
      {
        id: "email",
        label: "Email",
        href: "/communication/email",
        roles: "",
      },
      {
        id: "notification",
        label: "Notification",
        href: "/communication/notification",
        roles: "",
      },
    ],
  },
  {
    id: "student",
    icon: FaGraduationCap,
    label: "Student",
    href: "/students",
    roles: "",
    subItems: [
      {
        id: "studentlist",
        icon: FaList,
        label: "Student List",
        href: "/students",
        roles: "",
      },
      {
        id: "createstudent",
        icon: FaPlusCircle,
        label: "Add Student",
        href: "/students/create",
        roles: "",
      },
      {
        id: "importstudents",
        icon: FaFileImport,
        label: "Import Students",
        href: "/students/import",
        roles: "",
      },
    ],
  },
  {
    id: "setting",
    icon: FiSettings,
    label: "Settings",
    href: "/setting",
    roles: "",
    subItems: [
      {
        id: "system",
        label: "Communication Setting",
        href: "/setting/communication/preference",
        roles: "",
      },
      {
        id: "payment",
        label: "Payment Setting",
        href: "/setting/payment",
        roles: "",
      },
      {
        id: "about",
        label: "About",
        href: "/setting/about",
        roles: "",
      },
    ],
  },
];