import {
  FiGrid,
  FiDollarSign,
  FiClock,
  FiPackage,
  FiSettings,
  FiList,
  FiUserPlus,
  FiCamera,
  FiEye,
  FiClipboard,
  FiBarChart,
  FiActivity,
  FiTrendingUp,
  FiUsers,
  FiFileText,
} from "react-icons/fi";
import {
  FaSchool,
  FaRegPlusSquare,
  FaUsers,
  FaCalendarCheck,
  FaQrcode,
} from "react-icons/fa";

export const MENU_ITEMS = [
  {
    id: "dashboard",
    icon: FiGrid,
    label: "Dashboard",
    href: "/dashboard",
    roles: "",
  },
  {
    id: "school",
    icon: FaSchool,
    label: "School",
    href: "/school",
    roles: "",
  },
  {
    id: "createschool",
    icon: FaRegPlusSquare,
    label: "Create School",
    href: "/school/createschool",
    roles: "",
  },
  {
    id: "subscription",
    icon: FiDollarSign,
    label: "Subscription",
    href: "/subscription",
    roles: "",
  },
  {
    id: "pendingrequest",
    icon: FiClock,
    label: "Pending Request",
    href: "/pendingrequest",
    roles: "",
  },
  {
    id: "package",
    icon: FiPackage,
    label: "Package",
    href: "/package",
    roles: "",
  },
  {
    id: "academic",
    icon: FiSettings,
    label: "Academic",
    href: "/academic",
    roles: "",
    subItems: [
      {
        id: "subject",
        label: "Subject",
        href: "/academic/subject",
        roles: "",
      },
      {
        id: "class",
        label: "Class",
        href: "/academic/class",
        roles: "",
      },
      {
        id: "stream",
        label: "Stream",
        href: "/academic/stream",
        roles: "",
      },
      {
        id: "timetable",
        label: "Time Table",
        href: "/academic/timetable",
        roles: "",
      },
    ],
  },
  {
    id: "employee",
    icon: FaUsers,
    label: "Employees",
    href: "/employee",
    roles: "",
    subItems: [
      {
        id: "employee_list",
        icon: FiList,
        label: "Employee List",
        href: "/employee",
        roles: "",
      },
      {
        id: "add_employee",
        icon: FiUserPlus,
        label: "Add Employee",
        href: "/employee/addemployee",
        roles: "",
      },
    ],
  },
  {
    id: "attendance",
    icon: FaCalendarCheck,
    label: "Attendance",
    href: "/attendance",
    roles: "",
    subItems: [
      {
        id: "generate",
        icon: FaQrcode,
        label: "Generate QR Code",
        href: "/attendance/generate",
        roles: "",
      },
      {
        id: "scan",
        icon: FiCamera,
        label: "Scan QR Code",
        href: "/attendance/scan",
        roles: "",
      },
      {
        id: "list",
        icon: FiList,
        label: "Attendance List",
        href: "/attendance/list",
        roles: "",
      },
      {
        id: "view",
        icon: FiEye,
        label: "View Attendance",
        href: "/attendance/view",
        roles: "",
      },
    ],
  },
  {
    id: "assesment",
    icon: FiClipboard,
    label: "Assessment",
    href: "/assesment",
    roles: "",
    subItems: [
      {
        id: "assessment_list",
        icon: FiBarChart,
        label: "Assessment Entries",
        href: "/assesment",
        roles: "",
      },
      {
        id: "createanalytics",
        icon: FiActivity,
        label: "Assessment Analytics",
        href: "/assesment/analytics",
        roles: "",
      },
      {
        id: "progreess-trackers",
        icon: FiTrendingUp,
        label: "Progress Track",
        href: "/assesment/progress-tracker",
        roles: "",
      },
      {
        id: "roster",
        icon: FiUsers,
        label: "Roster",
        href: "/assesment/roster",
        roles: "",
      },
      {
        id: "report-card",
        icon: FiFileText,
        label: "Report Card",
        href: "/assesment/reportcard",
        roles: "",
      },
       
    ],
  },
  {
    id: "setting",
    icon: FiSettings,
    label: "Settings",
    href: "/setting",
    roles: "",
    subItems: [
      {
        id: "system",
        label: "System Setting",
        href: "/setting/system",
        roles: "",
      },
      {
        id: "payment",
        label: "Payment Setting",
        href: "/setting/payment",
        roles: "",
      },
      {
        id: "about",
        label: "About",
        href: "/setting/about",
        roles: "",
      },
    ],
  },
];