import {
  FaSchool,
  FaRegPlusSquare,
  FaUsers,
  FaCalendarCheck,
  FaQrcode,
  FaGraduationCap,
  FaPlusCircle,
  FaFileImport,
  FaList,
} from "react-icons/fa";
import { FiClock, FiDollarSign, FiEye, FiGrid, FiList, FiPackage, FiSettings, FiUserPlus, FiCamera } from "react-icons/fi";

export const MENU_ITEMS = [
  {
    id: "dashboard",
    icon: FiGrid,
    label: "Dashboard",
    href: "/dashboard",
    roles: ['ROLE_ADMIN','ROLE_STUDENT','ROLE_TEACHER','ROLE_PARENT'],
  },
  {
    id: "school",
    icon: FaSchool,
    label: "School",
    href: "/school",
    roles: ['ROLE_SUPERADMIN'],
  },
  {
    id: "createschool",
    icon: FaRegPlusSquare,
    label: "Create School",
    href: "/school/createschool",
    roles: ['ROLE_SUPERADMIN'],
  },
  {
    id: "subscription",
    icon: FiDollarSign,
    label: "Subscription",
    href: "/subscription",
    roles: ['ROLE_SUPERADMIN'],
  },
  {
    id: "pandingrequest",
    icon: FiClock,
    label: "Pending Request",
    href: "/pandingrequest",
    roles: ['ROLE_SUPERADMIN'],
  },
  {
    id: "package",
    icon: FiPackage,
    label: "Package",
    href: "/package",
    roles: ['ROLE_SUPERADMIN'],
  },
  {
    id: "academic",
    icon: FiSettings,
    label: "Academic",
    href: "/academic",
    roles: ['ROLE_ADMIN','ROLE_STUDENT','ROLE_TEACHER','ROLE_PARENT'],
    subItems: [
      {
        id: "subject",
        label: "Subject",
        href: "/academic/subject",
        roles: ['ROLE_TEACHER','ROLE_ADMIN'],
      },
      {
        id: "subject-class",
        label: "Subject Class",
        href: "/academic/subject/class",
        roles: ['ROLE_STUDENT','ROLE_PARENT'],
      },
      {
        id: "class",
        label: "Class",
        href: "/academic/class",
        roles: ['ROLE_ADMIN','ROLE_TEACHER'],
      },
      {
        id: "stream ",
        label: "Stream",
        href: "/academic/stream",
        roles: ['ROLE_ADMIN','ROLE_TEACHER'],
      },
      {
        id: "timetable",
        label: "Time Table",
        href: "/academic/timetable",
        roles: ['ROLE_ADMIN','ROLE_TEACHER'],
      },
    ],
  },
  {
    id: "employee",
    icon: FaUsers,
    label: "Employees",
    href: "/employee",
    roles: ['ROLE_ADMIN','ROLE_TEACHER'],
    subItems: [
      {
        id: "employee_List",
        icon: FiList,
        label: "Employee List",
        href: "/employee",
        roles: ['ROLE_ADMIN','ROLE_TEACHER'],
      },
      {
        id: "addEmployee",
        icon: FiUserPlus,
        label: "Add Employee",
        href: "/employee/addemployee",
        roles: ['ROLE_ADMIN'],
      },
    ],
  },
  {
    id: "attendance",
    icon: FaCalendarCheck,
    label: "Attendance",
    href: "/attendance",
    roles: ['ROLE_ADMIN','ROLE_STUDENT','ROLE_TEACHER','ROLE_PARENT'],
    subItems: [
      {
        id: "generate",
        icon: FaQrcode,
        label: "Generate QR Code",
        href: "/attendance/generate",
        roles: ['ROLE_ADMIN','ROLE_TEACHER'],
      },
      {
        id: "scan",
        icon: FiCamera,
        label: "Scan QR Code",
        href: "/attendance/scan",
        roles: ['ROLE_STUDENT','ROLE_TEACHER'],
      },
      {
        id: "list",
        icon: FiList,
        label: "Attendance List",
        href: "/attendance/list",
        roles: ['ROLE_ADMIN','ROLE_TEACHER'],
      },
      {
        id: "view",
        icon: FiEye,
        label: "View Attendance",
        href: "/attendance/view",
        roles: ['ROLE_PARENT','ROLE_ADMIN','ROLE_TEACHER','ROLE_STUDENT'],
      },
    ],
  },
  {
    id: "announcementandevent",
    icon: FiSettings,
    label: "Announcements",
    href: "/communication/event",
    roles: ['ROLE_PARENT','ROLE_ADMIN','ROLE_TEACHER','ROLE_STUDENT'], // Roles can be updated later for access control (e.g., "ROLE_ADMIN,ROLE_TEACHER")
    subItems: [
      {
        id: "event",
        label: "Events",
        href: "/communication/event",
        roles: ['ROLE_PARENT','ROLE_ADMIN','ROLE_TEACHER','ROLE_STUDENT'],
      },
      {
        id: "allEvents",
        label: "All Events",
        href: "/communication/event",
        roles: ['ROLE_PARENT','ROLE_ADMIN','ROLE_TEACHER','ROLE_STUDENT'],
      },
      {
        id: "createEvent",
        label: "Create Event",
        href: "/communication/event/create",
        roles: ['ROLE_ADMIN','ROLE_TEACHER'],
      },
      {
        id: "pendingApprovals",
        label: "Pending Approvals",
        href: "/communication/event/pending-approval",
        roles: ['ROLE_ADMIN'], // Restrict to ROLE_ADMINs; adjust based on your role system
      },
      {
        id: "myAnnouncement",
        label: "My Announcement",
        href: "/communication/event/my-pending",
        roles: ['ROLE_TEACHER'], // Available to all creators
      },
      {
        id: "draft",
        label: "My Draft",
        href: "/communication/event/draft",
        roles: ['ROLE_PARENT','ROLE_ADMIN','ROLE_TEACHER','ROLE_STUDENT'], // Available to all creators
      },
      {
        id: "email",
        label: "Email",
        href: "/communication/email",
        roles: ['ROLE_PARENT','ROLE_ADMIN','ROLE_TEACHER','ROLE_STUDENT'],
      },
      {
        id: "notification",
        label: "Notification",
        href: "/communication/notification",
        roles: ['ROLE_PARENT','ROLE_ADMIN','ROLE_TEACHER','ROLE_STUDENT'],
      },
    ],
  },
  {
    id: "student",
    icon: FaGraduationCap,
    label: "Student",
    href: "/students",
    roles: ['ROLE_PARENT','ROLE_ADMIN','ROLE_TEACHER','ROLE_STUDENT'],
    subItems: [
      {
        id: "studentlist",
        icon: FaList,
        label: "Student List",
        href: "/students",
        roles: ['ROLE_ADMIN','ROLE_TEACHER','ROLE_STUDENT'],
      },
      {
        id: "createstudent",
        icon: FaPlusCircle,
        label: "Add Student",
        href: "/students/create",
        roles: ['ROLE_ADMIN','ROLE_TEACHER'],
      },
      {
        id: "importstudents",
        icon: FaFileImport,
        label: "Import Students",
        href: "/students/import",
        roles: ['ROLE_ADMIN','ROLE_TEACHER'],
      },
    ],
  },
  {
    id: "usermanagement",
    icon: FaGraduationCap,
    label: "User Management",
    href: "/user",
    roles: ['ROLE_PARENT','ROLE_ADMIN','ROLE_TEACHER','ROLE_STUDENT','ROLE_SUPERADMIN'],
    subItems: [
      {
        id: "schooluserlist",
        icon: FaList,
        label: "School User",
        href: "/user/school",
        roles: ['ROLE_SUPERADMIN'],
      },
      {
        id: "userlist",
        icon: FaList,
        label: "User",
        href: "/user",
        roles: ['ROLE_ADMIN'],
      },
      {
        id: "rolelist",
        icon: FaPlusCircle,
        label: "Roles",
        href: "/user/role",
        roles: ['ROLE_ADMIN'],
      },
      {
        id: "permissionlist",
        icon: FaFileImport,
        label: "Permissions",
        href: "/user/permission",
        roles: ['ROLE_ADMIN'],
      },
      {
        id: "createuser",
        icon: FaList,
        label: "User Registration",
        href: "/user/create",
        roles: ['ROLE_ADMIN','ROLE_TEACHER'],
      },
      {
        id: "useractivity",
        icon: FaList,
        label: "User Activity",
        href: "/user-activity",
        roles: ['ROLE_ADMIN','ROLE_SUPERADMIN','ROLE_TEACHER'],
      },
      // {
      //   id: "rolelist",
      //   icon: FaPlusCircle,
      //   label: "Roles",
      //   href: "/user/role",
      //   roles: ['ROLE_ADMIN'],
      // },
      // {
      //   id: "permissionlist",
      //   icon: FaFileImport,
      //   label: "Permissions",
      //   href: "/user/permission",
      //   roles: ['ROLE_ADMIN'],
      // },
    ],
  },
  {
    id: "setting",
    icon: FiSettings,
    label: "Settings",
    href: "/setting",
    roles: ['ROLE_PARENT','ROLE_ADMIN','ROLE_TEACHER','ROLE_STUDENT','ROLE_SUPERADMIN'],
    subItems: [
      {
        id: "system",
        label: "Communication Setting",
        href: "/setting/communication/preference",
        roles: ['ROLE_PARENT','ROLE_ADMIN','ROLE_TEACHER','ROLE_STUDENT'],
      },
      {
        id: "payment ",
        label: "Payment Setting",
        href: "/setting/payment",
        roles: ['ROLE_PARENT','ROLE_ADMIN','ROLE_TEACHER','ROLE_STUDENT'],
      },
      {
        id: "about",
        label: "About",
        href: "/setting/about",
        roles: ['ROLE_PARENT','ROLE_ADMIN','ROLE_TEACHER','ROLE_STUDENT'],
      },
    ],
  },
];