spring:
  application:
    name: USER_SERVICE
    file:
      uploads:
        photos-output-path: ./uploads
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://mysql:3306/User_Service  
    username: admin  
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver  
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: wandimayew8@gmail.com
    password: jrbt rotv xjwz tfqk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  password-reset:
    token:
      expiration: 30 # minutes
  jwtSecret: zWR3i+mURw4kppEwVNhxZdqblotfvWseQGKI1SdLI9Y=
  jwtExpirationMs: 86400000
  
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8087
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/  # URL of the Eureka Server
    registerWithEureka: true  # Register this client with Eureka
    fetchRegistry: true 
  instance:
    preferIpAddress: true



