spring:
  application:
    name: User_Service
    file:
      uploads:
        photos-output-path: ./uploads
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/User_Service  
    username: root  
    password: root 
    driver-class-name: com.mysql.cj.jdbc.Driver  
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: wandimayew8@gmail.com
    password: jrbt rotv xjwz tfqk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
<<<<<<< HEAD
=======
  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      disable-swagger-default-url: true
springdoc:
  packages-to-scan:
  - com.schoolmanagement.User_Service
>>>>>>> 81b6b4b (Staff Service added)

app:
  password-reset:
    token:
      expiration: 30 # minutes
  jwtSecret: zWR3i+mURw4kppEwVNhxZdqblotfvWseQGKI1SdLI9Y=
  jwtExpirationMs: 86400000

server:
<<<<<<< HEAD
  port: 8082

=======
  port: 8082
>>>>>>> 81b6b4b (Staff Service added)
