server:
  port: 8761

eureka:
  client:
    registerWithEureka: false  # Eureka Server doesn't register itself
    fetchRegistry: false       # Eureka Server doesn't need to fetch registry
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost