package com.schoolmanagement.student_service.model;

import java.time.LocalDateTime;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.Data;

@Entity
@Data
public class QRCode {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long qrCodeId;

    @NotNull(message = "School ID cannot be null")
    private Long schoolId; 

    @NotNull(message = "Class ID cannot be null")
    private Long classId;  

    @NotNull(message = "Section ID cannot be null")
    private Long sectionId; 

    @NotNull(message = "qrCodeUUID cannot be null")
    private String qrCodeUUID;

    @PastOrPresent(message = "Generated time must be in the past or present")
    private LocalDateTime generatedTime;

    @Future(message = "Expiry time must be in the future")
    private LocalDateTime expiryTime;

    @NotBlank(message = "Session token cannot be blank")
    @Lob
    @Column(columnDefinition = "TEXT")
    private String sessionToken; 

    @NotBlank(message = "Generated by cannot be blank")
    private String generatedBy;

    @NotBlank(message = "QR code path cannot be blank")
    private String qrCodePath;

    @Enumerated(EnumType.STRING)
    @NotNull(message = "Status cannot be null")
    private QRCodeStatus status;

    public enum QRCodeStatus {
        ACTIVE, EXPIRED, INVALID
    }
}