package com.schoolmanagement.student_service.dto;

import com.schoolmanagement.student_service.model.QRCode.QRCodeStatus;
import jakarta.validation.constraints.*;
import lombok.Data;

import java.time.LocalDateTime;

@Data
public class QRCodeRequest {

    @NotNull(message = "School ID cannot be null")
    private Long schoolId;

    @NotNull(message = "Class ID cannot be null")
    private Long classId;

    @NotNull(message = "Section ID cannot be null")
    private Long sectionId;

    @PastOrPresent(message = "Generated time must be in the past or present")
    private LocalDateTime generatedTime;

    @Future(message = "Expiry time must be in the future")
    private LocalDateTime expiryTime;

    @NotBlank(message = "Session token cannot be blank")
    private String sessionToken;

    @NotBlank(message = "Generated by cannot be blank")
    private String generatedBy;

    @NotBlank(message = "QR code path cannot be blank")
    private String qrCodePath;

    @NotNull(message = "Status cannot be null")
    private QRCodeStatus status;
}