spring:
  application:
    name: TENANT_SERVICE
    file:
      uploads:
        photos-output-path: ./uploads
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/Tenant_Service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8084

app:
  jwtSecret: zWR3i+mURw4kppEwVNhxZdqblotfvWseQGKI1SdLI9Y=
  jwtExpirationMs: 86400000 # 24 hours in milliseconds

user:
  service:
    url: http://localhost:8085

tenant:
  service:
    token: this-is-me-do-you-remember-me


# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://10.194.61.74:8761/eureka/  # URL of the Eureka Server
#     registerWithEureka: true  # Register this client with Eureka
#     fetchRegistry: true  # Fetch the registry to discover other services
#   instance:
#     preferIpAddress: true  # Use IP address instead of hostname (optional but recommended)
#     # prefer-ip-address: true
#     ipAddress: 10.194.53.23  # Replace with Machine 2’s actual IP (e.g., 10.194.61.x)
#     hostname: 10.194.53.23  # Optional, ensures consistency
#     non-secure-port: 8084