spring:
  application:
    # name: ${SPRING_APPLICATION_NAME}
    name: tenant-service
    file:
      uploads:
        photos-output-path: ./uploads
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    # url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/Tenant_Service?createDatabaseIfNotExist=true
    # username: ${MYSQL_USER}
    username: root
    password: password
    # password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  # port: ${SERVER_PORT}
  port: 8081

app:
  jwtSecret: zWR3i+mURw4kppEwVNhxZdqblotfvWseQGKI1SdLI9Y=
  jwtExpirationMs: 86400000 # 24 hours in milliseconds

user:
  service:
    # url: ${USER_SERVICE}
    url: http://localhost:8080


tenant:
  service:
    token: this-is-me-do-you-remember-me

eureka:
  client:
    serviceUrl:
      # defaultZone: ${SERVICE_REGISTRY_URL}/eureka/
      defaultZone: http://localhost:8761/eureka
    enabled: true  # URL of the Eureka Server
    registerWithEureka: true  # Register this client with Eureka
    fetchRegistry: true 
  instance:
    # hostname: ${EUREKA_INSTANCE_HOSTNAME}
    hostname: localhost
    prefer-ip-address: false
