

services:
  # Communication Service
  mysql_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservice_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - microservice_network

  communication_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/Communication_Service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://10.194.61.74:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_IP_ADDRESS=10.194.53.23  # Machine 2 IP
      - EUREKA_INSTANCE_NON_SECURE_PORT=8081
      - SERVER_PORT=8081
    depends_on:
      mysql_db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - microservice_network

    
  academic_service:
    build:
      context: ../academic_service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/Academic_Service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://10.194.61.74:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_IP_ADDRESS=10.194.53.23  # Machine 2 IP
      - EUREKA_INSTANCE_NON_SECURE_PORT=8082
      - SERVER_PORT=8082
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - microservice_network

  student_service:
    build:
      context: ../student_service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/Student_Service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://10.194.61.74:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_IP_ADDRESS=10.194.53.23  # Machine 2 IP
      - EUREKA_INSTANCE_NON_SECURE_PORT=8083
      - SERVER_PORT=8083
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - microservice_network
    
  tenant_service:
    build:
      context: ../tenant_service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/Tenant_Service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://10.194.61.74:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_IP_ADDRESS=10.194.53.23  # Machine 2 IP
      - EUREKA_INSTANCE_NON_SECURE_PORT=8084
      - SERVER_PORT=8084
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - microservice_network

  user_service:
    build:
      context: ../User_Service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/User_Service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      # - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://10.194.61.74:8761/eureka/
      # - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      # - EUREKA_INSTANCE_IP_ADDRESS=10.194.53.23  # Machine 2 IP
      # - EUREKA_INSTANCE_NON_SECURE_PORT=8085
      - SERVER_PORT=8085
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - microservice_network

networks:
  microservice_network:
    driver: bridge

volumes:
  mysql_data: