spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            exposed-headers: "Access-Control-Allow-Origin"
            max-age: 3600
      routes:
        - id: User_Service
          uri: lb://user-management
          predicates:
            - Path=/auth/api/**

        - id: Tenant_Service
          uri: lb://tenant-service
          predicates:
            - Path=/tenant/api/**
        - id: Communication_Service_API
          uri: lb://communication-service
          predicates:
            - Path=/communication/api/**

        - id: Communication_Service_Notifications
          uri: lb://communication-service
          predicates:
            - Path=/notifications/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: false
    non-secure-port: 8080
    metadata-map:
      appName: API_GATEWAY

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /auth/v3/api-docs
        name: User Service
      - url: /academic/v3/api-docs
        name: Academic Service
    disable-swagger-default-url: true
    display-request-duration: true
    use-root-path: true
  api-docs:
    enabled: true
    resolve-schema-properties: true
  paths-to-match: /**
  cache:
    disabled: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springdoc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always