package com.schoolmanagement.User_Service.config;

import com.schoolmanagement.User_Service.model.PermissionTemplate;

import java.util.Arrays;
import java.util.List;

public class PermissionTemplateFactory {

        public static List<PermissionTemplate> createDefaultTemplates() {
                return Arrays.asList(

                                // AuthController (User Service)
                                new PermissionTemplate("LOGIN_USER",
                                                "Authenticate and log in a user",
                                                "/auth/api/login",
                                                "POST"),
                                new PermissionTemplate("VIEW_LOGIN_ACTIVITY",
                                                "View login activity for a school",
                                                "/auth/api/*/activity",
                                                "GET"),
                                new PermissionTemplate("REGISTER_USER",
                                                "Register a new user in a school",
                                                "/auth/api/*/register",
                                                "POST"),
                                new PermissionTemplate("LOGOUT_USER",
                                                "Logout and clear token",
                                                "/auth/api/logout",
                                                "POST"),
                                new PermissionTemplate("REGISTER_ADMIN",
                                                "Register an admin user",
                                                "/auth/api/register",
                                                "POST"),

                                // PasswordResetController Permissions
                                new PermissionTemplate("INITIATE_PASSWORD_RESET",
                                                "Initiate password reset process",
                                                "/auth/api/forgot-password",
                                                "POST"),
                                new PermissionTemplate("RESET_PASSWORD",
                                                "Reset user password",
                                                "/auth/api/reset-password",
                                                "POST"),
                                new PermissionTemplate("APPROVE_PASSWORD_RESET",
                                                "Approve a password reset request",
                                                "/auth/api/approve-password-reset",
                                                "POST"),
                                new PermissionTemplate("VIEW_PENDING_PASSWORD_RESETS",
                                                "View pending password reset requests",
                                                "/auth/api/pending-password-resets",
                                                "GET"),

                                // PermissionCheckController Permissions
                                new PermissionTemplate("CHECK_PERMISSION",
                                                "Internal API for checking permission",
                                                "/auth/api/internal/check-permission",
                                                "POST"),

                                // PermissionController Permissions
                                new PermissionTemplate("VIEW_ALL_PERMISSIONS",
                                                "View all permissions for school",
                                                "/auth/api/*/permissions",
                                                "GET"),
                                new PermissionTemplate("VIEW_PERMISSION_BY_ID",
                                                "View specific permission by ID",
                                                "/auth/api/*/permissions/*",
                                                "GET"),
                                new PermissionTemplate("CREATE_PERMISSION",
                                                "Create a new permission",
                                                "/auth/api/*/permissions",
                                                "POST"),
                                new PermissionTemplate("UPDATE_PERMISSION",
                                                "Update existing permission",
                                                "/auth/api/*/permissions/*",
                                                "PUT"),
                                new PermissionTemplate("DELETE_PERMISSION",
                                                "Delete a permission",
                                                "/auth/api/*/permissions/*",
                                                "DELETE"),
                                new PermissionTemplate("VIEW_PERMISSION_BY_NAME",
                                                "View permission by name",
                                                "/auth/api/*/permissions/name/*",
                                                "GET"),
                                new PermissionTemplate("VIEW_PERMISSION_BY_ROLE",
                                                "View permissions by role",
                                                "/auth/api/*/permissions/by-role/*",
                                                "GET"),
                                new PermissionTemplate("VIEW_PERMISSIONS_BY_USER",
                                                "View permissions by user",
                                                "/auth/api/*/permissions/by-user/*",
                                                "GET"),
                                new PermissionTemplate("REMOVE_PERMISSIONS_FROM_USER",
                                                "Remove permissions from user",
                                                "/auth/api/*/user/remove-permissions/*/*",
                                                "DELETE"),

                                // RoleController Permissions
                                new PermissionTemplate("VIEW_ROLE_BY_ID",
                                                "View specific role by ID",
                                                "/auth/api/*/roles/*",
                                                "GET"),
                                new PermissionTemplate("VIEW_ALL_ROLES",
                                                "View all roles for school",
                                                "/auth/api/*/roles",
                                                "GET"),
                                new PermissionTemplate("CREATE_ROLE",
                                                "Create a new role",
                                                "/auth/api/*/roles",
                                                "POST"),
                                new PermissionTemplate("UPDATE_ROLE",
                                                "Update existing role",
                                                "/auth/api/*/roles/*",
                                                "PUT"),
                                new PermissionTemplate("DELETE_ROLE",
                                                "Delete a role",
                                                "/auth/api/*/roles/*",
                                                "DELETE"),
                                new PermissionTemplate("ASSIGN_ROLE_TO_USER",
                                                "Assign role to user",
                                                "/auth/api/*/roles/*/assign/*",
                                                "POST"),
                                new PermissionTemplate("ASSIGN_PERMISSIONS_TO_ROLE",
                                                "Assign permissions to role",
                                                "/auth/api/*/roles/assign-permissions",
                                                "POST"),
                                new PermissionTemplate("REMOVE_ROLE_FROM_USER",
                                                "Remove role from user",
                                                "/auth/api/*/roles/remove-role",
                                                "DELETE"),
                                new PermissionTemplate("REMOVE_PERMISSIONS_FROM_ROLE",
                                                "Remove permissions from Role",
                                                "/auth/api/*/roles/remove-permissions/*/*",
                                                "DELETE"),

                                // SchoolPermissionController Permissions
                                new PermissionTemplate("BOOTSTRAP_PERMISSIONS",
                                                "Bootstrap permissions for a school",
                                                "/auth/api/internal/schools/*/bootstrap-permissions",
                                                "POST"),

                                // UserController Permissions
                                new PermissionTemplate("UPDATE_USER",
                                                "Update user details",
                                                "/auth/api/*/users/*",
                                                "PUT"),
                                new PermissionTemplate("VIEW_USER_BY_ID",
                                                "View specific user by ID",
                                                "/auth/api/*/users/*",
                                                "GET"),
                                new PermissionTemplate("VIEW_USERS_BY_ROLES",
                                                "View users by roles",
                                                "/auth/api/*/users/roles",
                                                "GET"),
                                new PermissionTemplate("DELETE_USER",
                                                "Delete a user",
                                                "/auth/api/*/users/*",
                                                "DELETE"),
                                new PermissionTemplate("VIEW_ALL_USERS_BY_SCHOOL",
                                                "View all users in school",
                                                "/auth/api/*/users",
                                                "GET"),
                                new PermissionTemplate("VIEW_USER_EMAIL",
                                                "View user email",
                                                "/auth/api/*/users/*/email",
                                                "GET"),
                                new PermissionTemplate("VIEW_USER_IDS_BY_ROLE",
                                                "View user IDs by role",
                                                "/auth/api/*/users/role",
                                                "GET"),
                                new PermissionTemplate("CHANGE_PASSWORD",
                                                "Change user password",
                                                "/auth/api/*/change-password",
                                                "PUT"),
                                new PermissionTemplate("VIEW_USER_COUNTS_BY_ROLE",
                                                "View user counts by role",
                                                "/auth/api/*/users-counts",
                                                "GET"), // Adjusted to match endpoint
                                new PermissionTemplate("VIEW_SCHOOL_ADMINS",
                                                "View the Admin of all registered school on the system",
                                                "/auth/api/getAllAdmins",
                                                "GET"),
                                new PermissionTemplate("VIEW_SCHOOL_ADMINS_ACTIVITY",
                                                "View Admins Activity of all registered school on the system",
                                                "/auth/api/getAllAdminActivity",
                                                "GET"),

                                // Tenant Service Permissions (AddressController)
                                new PermissionTemplate("ADD_ADDRESS",
                                                "Add a new address",
                                                "/tenant/api/*/addNewAddress",
                                                "POST"),
                                new PermissionTemplate("EDIT_ADDRESS",
                                                "Edit an address",
                                                "/tenant/api/*/editAddressById/*",
                                                "PUT"),
                                new PermissionTemplate("VIEW_ALL_ADDRESSES",
                                                "View all addresses by school",
                                                "/tenant/api/*/getAllAddressBySchool",
                                                "GET"),
                                new PermissionTemplate("VIEW_ADDRESS_BY_ID",
                                                "View address by ID",
                                                "/tenant/api/*/getAddressById/*",
                                                "GET"),
                                new PermissionTemplate("DELETE_ADDRESS",
                                                "Delete address by ID",
                                                "/tenant/api/*/deleteAddressById/*",
                                                "DELETE"),

                                // Tenant Service Permissions (SchoolSubscriptionController)
                                new PermissionTemplate("ADD_SCHOOL_SUBSCRIPTION",
                                                "Add a new school subscription",
                                                "/tenant/api/*/addNewSchoolSubscription",
                                                "POST"),
                                new PermissionTemplate("EDIT_SCHOOL_SUBSCRIPTION",
                                                "Edit a school subscription",
                                                "/tenant/api/*/editSchoolSubscriptionById/*",
                                                "PUT"),
                                new PermissionTemplate("DELETE_SCHOOL_SUBSCRIPTION",
                                                "Delete school subscription by ID",
                                                "/tenant/api/*/deleteSchoolSubscriptionById/*",
                                                "DELETE"),
                                new PermissionTemplate("VIEW_ALL_SCHOOL_SUBSCRIPTIONS",
                                                "View all school subscriptions",
                                                "/tenant/api/*/getAllSchoolSubscriptions",
                                                "GET"),
                                new PermissionTemplate("VIEW_SUBSCRIPTIONS_BY_STATUS",
                                                "View subscriptions by status",
                                                "/tenant/api/getSubscriptionPending/*",
                                                "GET"),
                                new PermissionTemplate("VIEW_SCHOOL_SUBSCRIPTION_BY_STATUS",
                                                "View school subscription by status",
                                                "/tenant/api/*/getSchoolSubscriptionByStatus/*",
                                                "GET"),
                                new PermissionTemplate("MAKE_SUBSCRIPTION_PAYMENT",
                                                "Make a subscription payment",
                                                "/tenant/api/makeSubscriptionPayment",
                                                "POST"),
                                new PermissionTemplate("APPROVE_SUBSCRIPTION_PAYMENT",
                                                "Approve a subscription payment",
                                                "/tenant/api/makeSubscriptionPaid",
                                                "POST"),
                                new PermissionTemplate("VIEW_SCHOOL_SUBSCRIPTION_BY_ID",
                                                "View school subscription by ID",
                                                "/tenant/api/*/getSchoolSubscriptionById/*",
                                                "GET"),

                                // Tenant Service Permissions (SchoolController)
                                new PermissionTemplate("ADD_SCHOOL",
                                                "Add a new school",
                                                "/tenant/api/addNewSchool",
                                                "POST"),
                                new PermissionTemplate("EDIT_SCHOOL",
                                                "Edit an existing school",
                                                "/tenant/api/editSchoolById/*",
                                                "PUT"),
                                new PermissionTemplate("VIEW_ALL_SCHOOLS",
                                                "View all schools",
                                                "/tenant/api/getAllSchools",
                                                "GET"),
                                new PermissionTemplate("VIEW_SCHOOL_BY_ID",
                                                "View school by ID",
                                                "/tenant/api/getSchoolById/*",
                                                "GET"),
                                new PermissionTemplate("DELETE_SCHOOL_BY_ID",
                                                "Delete school by ID",
                                                "/tenant/api/deleteSchoolById/*",
                                                "DELETE"),
                                new PermissionTemplate("VIEW_SCHOOL_STATS",
                                                "View school statistics",
                                                "/tenant/api/getSchoolStats/*",
                                                "GET"),
                                new PermissionTemplate("VIEW_SCHOOL_NAME",
                                                "View schools names",
                                                "/tenant/api/getSchoolName/*",
                                                "GET"),
                                new PermissionTemplate("VIEW_SCHOOL_COUNT",
                                                "View the Numbers of school registered on the system",
                                                "/tenant/api/getSchoolCount",
                                                "GET"),

                                // Tenant Service Permissions (SubscriptionPlanController)
                                new PermissionTemplate("ADD_SUBSCRIPTION_PLAN",
                                                "Add a new subscription plan",
                                                "/tenant/api/addNewSubscriptionPlan",
                                                "POST"),
                                new PermissionTemplate("EDIT_SUBSCRIPTION_PLAN",
                                                "Edit a subscription plan",
                                                "/tenant/api/editSubscriptioPlanById/*",
                                                "PUT"),
                                new PermissionTemplate("VIEW_ALL_SUBSCRIPTION_PLANS",
                                                "View all subscription plans",
                                                "/tenant/api/getAllSubscriptionPlans",
                                                "GET"),
                                new PermissionTemplate("VIEW_SUBSCRIPTION_PLAN_BY_ID",
                                                "View subscription plan by ID",
                                                "/tenant/api/getSubscriptionPlanById/*",
                                                "GET"),
                                new PermissionTemplate("DELETE_SUBSCRIPTION_PLAN",
                                                "Delete subscription plan by ID",
                                                "/tenant/api/deleteSubscriptioPlanById/*",
                                                "DELETE"),
                                new PermissionTemplate("VIEW_SCHOOLS_BY_PLAN",
                                                "View schools subscribed to a plan",
                                                "/tenant/api/getSchoolsByPlanId/*",
                                                "GET"),

                                // Academic Service Permissions (ClassController)
                                new PermissionTemplate("ADD_CLASS",
                                                "Add a new class",
                                                "/academic/api/*/addNewClass",
                                                "POST"),
                                new PermissionTemplate("EDIT_CLASS",
                                                "Edit a class",
                                                "/academic/api/*/editClassById/*",
                                                "PUT"),
                                new PermissionTemplate("EDIT_CLASS_STATUS",
                                                "Edit class status",
                                                "/academic/api/*/editStatus/*",
                                                "PUT"),
                                new PermissionTemplate("VIEW_ALL_CLASSES_BY_SCHOOL",
                                                "View all classes by school",
                                                "/academic/api/*/getAllClassBySchool",
                                                "GET"),
                                new PermissionTemplate("VIEW_ALL_CLASSES_BY_STREAM",
                                                "View all classes by stream",
                                                "/academic/api/*/getAllClassByStream/*",
                                                "GET"),
                                new PermissionTemplate("VIEW_CLASS_BY_ID",
                                                "View class by ID",
                                                "/academic/api/*/getClassById/*",
                                                "GET"),
                                new PermissionTemplate("VIEW_CLASS_DETAILS",
                                                "View class details",
                                                "/academic/api/*/getClassDetails/*",
                                                "GET"),
                                new PermissionTemplate("DELETE_CLASS", "Delete class by ID",
                                                "/academic/api/*/deleteClassById/*",
                                                "DELETE"),
                                new PermissionTemplate("ASSIGN_SUBJECTS_TO_CLASS", "Assign subjects to class",
                                                "/academic/api/*/assign-subjects/*", "POST"),

                                // Academic Service Permissions (SectionController)
                                new PermissionTemplate("ADD_SECTION",
                                                "Add a new section",
                                                "/academic/api/*/addNewSection",
                                                "POST"),
                                new PermissionTemplate("EDIT_SECTION",
                                                "Edit a section",
                                                "/academic/api/*/editSectionById/*",
                                                "PUT"),
                                new PermissionTemplate("VIEW_ALL_SECTIONS_BY_CLASS",
                                                "View all sections by class",
                                                "/academic/api/*/getAllSectionByClass/*",
                                                "GET"),
                                new PermissionTemplate("VIEW_SECTION_BY_ID",
                                                "View section by ID",
                                                "/academic/api/*/getSectionById/*",
                                                "GET"),
                                new PermissionTemplate("DELETE_SECTION_BY_ID",
                                                "Delete section by ID",
                                                "/academic/api/*/deleteSectionById/*",
                                                "DELETE"),
                                new PermissionTemplate("DELETE_SECTIONS_BY_CLASS",
                                                "Delete sections by class",
                                                "/academic/api/*/deleteSectionByClass/*",
                                                "DELETE"),

                                // Academic Service Permissions (StreamController)
                                new PermissionTemplate("ADD_STREAM",
                                                "Add a new stream",
                                                "/academic/api/*/addNewStream",
                                                "POST"),
                                new PermissionTemplate("EDIT_STREAM",
                                                "Edit a stream",
                                                "/academic/api/*/editStreamById/*",
                                                "PUT"),
                                new PermissionTemplate("VIEW_ALL_STREAMS_BY_SCHOOL",
                                                "View all streams by school",
                                                "/academic/api/*/getAllStreamBySchool",
                                                "GET"),
                                new PermissionTemplate("VIEW_STREAM_BY_ID",
                                                "View stream by ID",
                                                "/academic/api/*/getStreamById/*",
                                                "GET"),
                                new PermissionTemplate("DELETE_STREAM",
                                                "Delete stream by ID",
                                                "/academic/api/*/deleteStreamById/*",
                                                "DELETE"),

                                // Academic Service Permissions (SubjectController)
                                new PermissionTemplate("ADD_SUBJECT",
                                                "Add a new subject",
                                                "/academic/api/*/addNewSubject",
                                                "POST"),
                                new PermissionTemplate("EDIT_SUBJECT",
                                                "Edit a subject",
                                                "/academic/api/*/editSubjectById/*",
                                                "PUT"),
                                new PermissionTemplate("VIEW_ALL_SUBJECTS_BY_CLASS",
                                                "View all subjects by class",
                                                "/academic/api/*/getAllSubjectByClass/*",
                                                "GET"),
                                new PermissionTemplate("VIEW_ALL_SUBJECTS_BY_STREAM",
                                                "View all subjects by stream",
                                                "/academic/api/*/getAllSubjectsByStream/*",
                                                "GET"),
                                new PermissionTemplate("VIEW_ALL_SUBJECTS_BY_SCHOOL",
                                                "View all subjects by school",
                                                "/academic/api/*/getAllSubjectBySchool",
                                                "GET"),
                                new PermissionTemplate("VIEW_SUBJECT_BY_ID",
                                                "View subject by ID",
                                                "/academic/api/*/getSubjectById/*",
                                                "GET"),
                                new PermissionTemplate("DELETE_SUBJECT",
                                                "Delete subject by ID",
                                                "/academic/api/*/deleteSubjectById/*",
                                                "DELETE"),

                                // Academic Service Permissions (TimeTableController)
                                new PermissionTemplate("ADD_TIMETABLE", "Add a new timetable",
                                                "/academic/api/*/addNewTimeTable",
                                                "POST"),
                                new PermissionTemplate("EDIT_TIMETABLE", "Edit a timetable",
                                                "/academic/api/*/editTimeTableById/*",
                                                "PUT"),
                                new PermissionTemplate("VIEW_ALL_TIMETABLES_BY_CLASS",
                                                "View all timetables by class",
                                                "/academic/api/*/getAllTimeTableByClass/*",
                                                "GET"),
                                new PermissionTemplate("VIEW_TIMETABLE_BY_ID",
                                                "View timetable by ID",
                                                "/academic/api/*/getTimeTableById/*",
                                                "GET"),
                                new PermissionTemplate("VIEW_TIMETABLE_BY_STREAM",
                                                "View timetable by stream",
                                                "/academic/api/*/getTimeTableByStream/*",
                                                "GET"),
                                new PermissionTemplate("DELETE_TIMETABLE_BY_ID",
                                                "Delete timetable by ID",
                                                "/academic/api/*/deleteTimeTableById/*",
                                                "DELETE"),
                                new PermissionTemplate("DELETE_TIMETABLES_BY_CLASS",
                                                "Delete timetables by class",
                                                "/academic/api/*/deleteTimeTableByClass/*",
                                                "DELETE"),

                                // Communication Service (Announcement Controller)
                                // AnnouncementController Permissions
                                new PermissionTemplate(
                                                "VIEW_ANNOUNCEMENT_BY_ID",
                                                "View a specific announcement by its ID",
                                                "/communication/api/*/getAnnouncementById/*",
                                                "GET"),
                                new PermissionTemplate(
                                                "VIEW_ALL_ANNOUNCEMENTS",
                                                "View all active announcements for a school",
                                                "/communication/api/*/getAllAnnouncements",
                                                "GET"),
                                new PermissionTemplate(
                                                "CREATE_ANNOUNCEMENT",
                                                "Create a new announcement",
                                                "/communication/api/*/createAnnouncement",
                                                "POST"),
                                new PermissionTemplate(
                                                "UPDATE_ANNOUNCEMENT",
                                                "Update an existing announcement",
                                                "/communication/api/*/updateAnnouncement/*",
                                                "PUT"),
                                new PermissionTemplate(
                                                "APPROVE_ANNOUNCEMENT",
                                                "Approve an announcement, setting its status to PUBLISHED",
                                                "/communication/api/*/approveAnnouncement/*/approve",
                                                "PUT"),
                                new PermissionTemplate(
                                                "REQUEST_APPROVAL_ANNOUNCEMENT",
                                                "Request approval for an announcement, setting its status to PENDING",
                                                "/communication/api/*/requestApprove/*/request-approval",
                                                "PUT"),
                                new PermissionTemplate(
                                                "VIEW_PENDING_APPROVALS",
                                                "View all announcements pending approval for a school",
                                                "/communication/api/*/getAllRequestApproval/pending-approval",
                                                "GET"),
                                new PermissionTemplate(
                                                "VIEW_CREATOR_PENDING_ANNOUNCEMENTS",
                                                "View all pending announcements created by the authenticated user",
                                                "/communication/api/*/announcements/creator-pending",
                                                "GET"),
                                new PermissionTemplate(
                                                "VIEW_MY_ANNOUNCEMENTS",
                                                "View all non-pending announcements created by the authenticated user",
                                                "/communication/api/*/announcements/my-announcements",
                                                "GET"),
                                new PermissionTemplate(
                                                "VIEW_MY_ANNOUNCEMENTS_DRAFT",
                                                "View all draft announcements created by the authenticated user",
                                                "/communication/api/*/announcements/my-announcements/status-draft",
                                                "GET"),
                                new PermissionTemplate(
                                                "CANCEL_ANNOUNCEMENT",
                                                "Cancel an announcement, setting its status back to DRAFT",
                                                "/communication/api/*/cancelAnnouncement/*/cancel",
                                                "PUT"),
                                new PermissionTemplate(
                                                "UPDATE_ANNOUNCEMENT_STATUS",
                                                "Update the status of an announcement",
                                                "/communication/api/*/updateAnnouncementStatus/*/status",
                                                "PUT"),
                                new PermissionTemplate(
                                                "DELETE_ANNOUNCEMENT",
                                                "Delete an announcement (soft delete)",
                                                "/communication/api/*/deleteAnnouncement/*",
                                                "DELETE"),

                                // CommunicationPreferenceController Permissions
                                new PermissionTemplate(
                                                "VIEW_COMMUNICATION_PREFERENCE_BY_ID",
                                                "View communication preference by its ID",
                                                "/communication/api/*/getCommunicationPreferenceById/*",
                                                "GET"),
                                new PermissionTemplate(
                                                "VIEW_COMMUNICATION_PREFERENCE_BY_USER",
                                                "View communication preference for the authenticated user",
                                                "/communication/api/*/getCommunicationPreferenceByUserId",
                                                "GET"),
                                new PermissionTemplate(
                                                "VIEW_ALL_COMMUNICATION_PREFERENCES",
                                                "View all communication preferences for a school",
                                                "/communication/api/*/getAllCommunicationPreference",
                                                "GET"),
                                new PermissionTemplate(
                                                "CREATE_COMMUNICATION_PREFERENCE",
                                                "Create a new communication preference",
                                                "/communication/api/*/createCommunicationPreference",
                                                "POST"),
                                new PermissionTemplate(
                                                "UPDATE_COMMUNICATION_PREFERENCE",
                                                "Update an existing communication preference",
                                                "/communication/api/*/updateCommunicationPreference/*",
                                                "PUT"),
                                new PermissionTemplate(
                                                "DELETE_COMMUNICATION_PREFERENCE",
                                                "Delete a communication preference",
                                                "/communication/api/*/deleteCommunicationPreference/*",
                                                "DELETE"),

                                // EmailMessageController Permissions
                                new PermissionTemplate(
                                                "COMPOSE_EMAIL",
                                                "Compose and optionally send an email",
                                                "/communication/api/*/compose",
                                                "POST"),
                                new PermissionTemplate(
                                                "VIEW_EMAILS_BY_FOLDER",
                                                "View emails in a specific folder with pagination",
                                                "/communication/api/*/getEmailsByFolder/*",
                                                "GET"),
                                new PermissionTemplate(
                                                "VIEW_EMAIL_BY_ID",
                                                "View a specific email by its ID",
                                                "/communication/api/*/getEmailsById/detail/*",
                                                "GET"),
                                new PermissionTemplate(
                                                "UPDATE_EMAIL_STATUS",
                                                "Update the status of an email",
                                                "/communication/api/*/updateEmailStatus/*/status",
                                                "PUT"),
                                new PermissionTemplate(
                                                "MARK_EMAIL_AS_READ",
                                                "Mark an email as read",
                                                "/communication/api/*/markEmailAsRead/*/read",
                                                "PUT"),
                                new PermissionTemplate(
                                                "DELETE_EMAIL",
                                                "Delete an email (soft delete)",
                                                "/communication/api/*/deleteEmail/*",
                                                "DELETE"),

                                // NotificationController Permissions
                                new PermissionTemplate(
                                                "VIEW_NOTIFICATION_BY_ID",
                                                "View a specific notification by its ID",
                                                "/communication/api/*/getNotificationById/*",
                                                "GET"),
                                new PermissionTemplate(
                                                "VIEW_ALL_NOTIFICATIONS",
                                                "View all notifications for a school",
                                                "/communication/api/*/getAllNotification",
                                                "GET"),
                                new PermissionTemplate(
                                                "CREATE_NOTIFICATION",
                                                "Create a new notification",
                                                "/communication/api/*/createNotification",
                                                "POST"),
                                new PermissionTemplate(
                                                "UPDATE_NOTIFICATION",
                                                "Update an existing notification",
                                                "/communication/api/*/updateNotification/*",
                                                "PUT"),
                                new PermissionTemplate(
                                                "DELETE_NOTIFICATION",
                                                "Delete a notification",
                                                "/communication/api/*/deleteNotification/*",
                                                "DELETE"),
                                new PermissionTemplate(
                                                "VIEW_UNREAD_NOTIFICATIONS",
                                                "View unread notifications for the authenticated user",
                                                "/communication/api/*/notifications/unread",
                                                "GET"),
                                new PermissionTemplate(
                                                "MARK_NOTIFICATION_AS_READ",
                                                "Mark a notification as read",
                                                "/communication/api/*/mark-read/notifications/*",
                                                "POST"),

                                // NotificationTemplateController Permissions
                                new PermissionTemplate(
                                                "VIEW_NOTIFICATION_TEMPLATE_BY_ID",
                                                "View a specific notification template by its ID",
                                                "/communication/api/*/getNotificationTemplateById/*",
                                                "GET"),
                                new PermissionTemplate(
                                                "VIEW_ALL_NOTIFICATION_TEMPLATES",
                                                "View all notification templates for a school",
                                                "/communication/api/*/getAllNotificationTemplate",
                                                "GET"),
                                new PermissionTemplate(
                                                "CREATE_NOTIFICATION_TEMPLATE",
                                                "Create a new notification template",
                                                "/communication/api/*/createNotificationTemplate",
                                                "POST"),
                                new PermissionTemplate(
                                                "UPDATE_NOTIFICATION_TEMPLATE",
                                                "Update an existing notification template",
                                                "/communication/api/*/updateNotificationTemplate/*",
                                                "PUT"),
                                new PermissionTemplate(
                                                "DELETE_NOTIFICATION_TEMPLATE",
                                                "Delete a notification template",
                                                "/communication/api/*/deleteNotificationTemplate/*",
                                                "DELETE")

                );
        }
}